version: "3"
services:
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8886:8081"

# docker run --init --name pgweb --restart always --detach --publish 8886:8081 sosedoff/pgweb