---
#------------------------------------------------------------------------------
# Install Grafana
#------------------------------------------------------------------------------
- name: Make sure grafana installed
  tags: grafana_install
  package: name=grafana state=present

#------------------------------------------------------------------------------
# Stop Grafana
#------------------------------------------------------------------------------
- name: Stop grafana service
  ignore_errors: true
  tags: grafana_stop
  systemd: name=grafana-server state=stopped enabled=yes daemon_reload=yes

#------------------------------------------------------------------------------
# Plugins Installation
#------------------------------------------------------------------------------
- import_tasks: plugins.yml
  tags: grafana_plugin_list

#------------------------------------------------------------------------------
# Config Grafana
#------------------------------------------------------------------------------
- import_tasks: config.yml
  tags: grafana_config

#------------------------------------------------------------------------------
# Launch Grafana
#------------------------------------------------------------------------------
- import_tasks: launch.yml
  tags: grafana_launch

#------------------------------------------------------------------------------
# Provision Pigsty Dashboards
#------------------------------------------------------------------------------
- import_tasks: provision.yml
  ignore_errors: yes
  tags: grafana_provision

...