---
#-----------------------------------------------------------------
# DOCKER
#-----------------------------------------------------------------
docker_enabled: false             # enable docker on this node?
docker_cgroups_driver: systemd    # docker cgroup fs driver: cgroupfs,systemd
docker_registry_mirrors: []       # docker registry mirror list
docker_exporter_port: 9323        # docker metrics exporter port, 9323 by default
docker_image: []                  # docker image to be pulled after bootstrap
docker_image_cache:               # docker image cache file/glob, `/tmp/docker` by default
  - /tmp/docker/*.tgz

#-----------------------------------------------------------------
# NODE_ADMIN (Reference)
#-----------------------------------------------------------------
node_admin_username: dba          # name of this admin user, dba by default
#-----------------------------------------------------------------
# PROMETHEUS (Reference)
#-----------------------------------------------------------------
prometheus_sd_dir: /etc/prometheus/targets # prometheus file service discovery directory
...