---
#------------------------------------------------------------------------------
# NODE EXPORTER
#------------------------------------------------------------------------------
node_exporter_enabled: true       # setup node_exporter on instance
node_exporter_port: 9100          # default port for node exporter
node_exporter_options: '--no-collector.softnet --no-collector.nvme --collector.ntp --collector.tcpstat --collector.processes'

#-----------------------------------------------------------------
# EXPORTER
#-----------------------------------------------------------------
exporter_install: none           # none|yum|binary, none by default
exporter_repo_url: ''            # if set, repo will be added to /etc/yum.repos.d/
exporter_metrics_path: /metrics  # default metric path for pg related exporter
...