---
#--------------------------------------------------------------#
# PostgreSQL Bash Scripts                               [pg_bin]
#--------------------------------------------------------------#
# sync files/postgres -> /pg/bin/
- name: copy /pg/bin/ scripts
  tags: pg_bin
  synchronize: src=postgres/ dest=/pg/bin/ owner={{ pg_dbsu }} group=postgres mode=0755


#--------------------------------------------------------------#
# PostgreSQL Alias & Shortcuts                        [pg_alias]
#--------------------------------------------------------------#
- name: copy postgres alias profile
  tags: pg_alias
  copy: src=pg-alias.sh dest=/etc/profile.d/pg-alias.sh mode=0644


#--------------------------------------------------------------#
# PostgreSQL ~/.pgsqlrc for PSQL Client                [pg_psql]
#--------------------------------------------------------------#
- name: copy psqlrc to postgres home
  tags: pg_psql
  copy: src=psqlrc dest="{{ pg_dbsu_home }}/.psqlrc" owner={{ pg_dbsu }} group=postgres mode=0600


#--------------------------------------------------------------#
# PostgreSQL dummy disk placeholder                   [pg_dummy]
#--------------------------------------------------------------#
# dummy file could be removed in case of disk-full which cushion against immediate failure
- name: create dummy placeholder file
  tags: pg_dummy
  command: fallocate -l {{ pg_dummy_filesize }} /pg/dummy


...