version: "3"
services:

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://dbuser_dba:DBUser.DBA@10.10.10.10:5432/meta
      PGRST_DB_SCHEMA: pigsty
      PGRST_DB_ANON_ROLE: dbuser_dba
      PGRST_SERVER_PORT: 8884
      PGRST_JWT_SECRET: some-random-secret
    ports:
      - "8884:8884"
