---
# - postgres monitor settings - #
exporter_metric_path: /metrics
node_exporter_port: 9100
pg_exporter_port: 9630
pg_exporter_config: pg_exporter.yaml
pgbouncer_exporter_port: 9631
pg_localhost: /var/run/postgresql

# - postgres variables reference - #
pg_port: 5432
pgbouncer_port: 6432
pg_default_database: postgres
pg_monitor_username: dbuser_monitor
pg_monitor_password: dbuser_monitor
...