---
galaxy_info:
  role_name: redis_remove
  description: remove redis instance & cluster from pigsty nodes
  min_ansible_version: "2.9"
  author: 'Ruohang Feng'
  license: GPLv3
  platforms:
    - name: EL
      versions: [ 7, 8 , 9 ]
    - name: Ubuntu
      versions: [ 22.04, 20.04 ]
    - name: Debian
      versions: [ 12, 11 ]
  galaxy_tags:
    - pigsty
    - redis
    - uninstall
...