---
################################################################
# Runs on normal node
################################################################

#--------------------------------------------------------------#
# register service to dcs
#--------------------------------------------------------------#
# runs on target node
- import_tasks: consul.yml
  tags: register_consul
  when: dcs_registry == 'consul'

# TODO: etcd service registry

################################################################
# Runs on meta node
################################################################

#--------------------------------------------------------------#
# register exporter targets to prometheus
#--------------------------------------------------------------#
- import_tasks: prometheus.yml
  when: prometheus_enabled|bool
  tags: register_prometheus


#--------------------------------------------------------------#
# register pgsql datasource to grafana
#--------------------------------------------------------------#
- import_tasks: grafana.yml
  when: grafana_enabled|bool
  tags: register_grafana


#--------------------------------------------------------------#
# register haproxy to nginx
#--------------------------------------------------------------#
- import_tasks: nginx.yml
  tags: register_nginx


#--------------------------------------------------------------#
# TODO: CMDB Register (if cmdb is used instead of inventory file)
#--------------------------------------------------------------#
# - import_tasks: cmdb.yml
#   tags: register_cmdb

#--------------------------------------------------------------#
# TODO: DNS Register (apply for DNS name)
#--------------------------------------------------------------#

#--------------------------------------------------------------#
# TODO: CA Register (apply for Certification)
#--------------------------------------------------------------#

...
