---
#--------------------------------------------------------------#
# Register PGSQL Target to Prometheus
#--------------------------------------------------------------#

#- name: Deregister pgsql exporter from prometheus
#  tags: [ pg_deregister , deregister_prometheus ]
#  delegate_to: '{{ item }}'
#  with_items: '{{ groups["meta"] }}'
#  file: path=/etc/prometheus/targets/pgsql/{{ pg_cluster }}-{{ pg_seq }}.yml state=absent

# prometheus are idempotent on multiple meta nodes
# /etc/prometheus/targets/pgsql/{{ pg_instance }}.yml
- name: register postgres to prometheus
  tags: [ pgsql_register, pg_register ]
  delegate_to: '{{ item }}'
  with_items: '{{ groups["meta"] }}'
  ignore_errors: true
  copy:
    dest: /etc/prometheus/targets/pgsql/{{ pg_cluster }}-{{ pg_seq }}.yml
    content: |
      # {{ pg_cluster }}-{{ pg_seq }} [{{ pg_role }}] @ {{ inventory_hostname }}
      - labels: { cls: {{ pg_cluster }}, ins: {{ pg_cluster }}-{{ pg_seq }}, ip: {{ inventory_hostname }} }
        targets: 
          {% if pg_exporter_enabled|bool %}- {{ inventory_hostname }}:{{ pg_exporter_port }}{% endif %}
      
          {% if pgbouncer_exporter_enabled|bool %}- {{ inventory_hostname }}:{{ pgbouncer_exporter_port }}{% endif %}
      
          {% if patroni_enabled|bool and patroni_mode != 'remove'  %}- {{ inventory_hostname }}:{{ patroni_port }}{% endif %}
      
          {% if haproxy_enabled|bool %}- {{ inventory_hostname }}:{{ haproxy_exporter_port }}{% endif %}

...