---
- name: Node features setup
  tags: node_feature
  ignore_errors: true
  block:

    # - disable numa - #
    - name: Node configure disable numa
      when: node_disable_numa
      script: disable_numa.sh


    # - disable swap - #
    - name: Node configure disable swap
      when: node_disable_swap
      command: swapoff -a

    - name: Node configure unmount swap
      when: node_disable_swap
      mount: name={{ item }} fstype=swap state=absent
      with_items: [swap, none]


    # - static network - #
    - name: Node setup static network
      when: node_static_network
      script: static_network.sh

    - name: Node configure disable firewall
      when: node_disable_firewall
      systemd: name=NetworkManager state=stopped enabled=no


    # - eanble disk prefetch - #
    - name: Node configure disk prefetch
      when: node_disk_prefetch
      script: disk_prefetch.sh

...
