---
#------------------------------------------------------------------------------
# Add tuned profile
#------------------------------------------------------------------------------
- name: Node tuned
  tags: node_tuned
  when: node_tune is defined and node_tune != 'none'
  block:
    - name: Get config parameter page count
      command: getconf _PHYS_PAGES
      register: node_page_count  # half mem in pages

    - name: Get config parameter page size
      shell: getconf PAGE_SIZE
      register: node_page_size  # half mem in bytes

    - name: Tune shmmax and shmall via mem
      when: node_page_count.stdout|int > 1048576
      set_fact:
        param_shmall: "{{ ((node_page_count.stdout|int) / 2)|int }}"
        param_shmmax: "{{ ((node_page_count.stdout|int) * (node_page_size.stdout|int) / 2)|int }}"

    - name: Create tuned profiles
      file: path=/etc/tuned/{{ item }} state=directory mode=0755
      with_items:
        - oltp
        - olap
        - crit
        - tiny

    - name: Render tuned profiles
      template: src=tuned-{{ item }}.conf dest=/etc/tuned/{{ item }}/tuned.conf mode=0644
      with_items:
        - oltp
        - olap
        - crit
        - tiny

    - name: Active tuned profile
      ignore_errors: true
      command: tuned-adm profile {{ node_tune }}

    - name: Change additional sysctl params
      ignore_errors: true
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
      with_dict: "{{ node_sysctl_params }}"
...
