---
################################################################
# check inventory and set facts
################################################################
- name: Check inventory and set fact
  tags: [always, pg_precheck]
  block:
    - name: Check cluster role seq exists
      assert:
        that:
          - cluster is defined
          - seq is defined
          - role is defined
        fail_msg: "host variable <cluster> and <seq> are required for init cluster"

    - name: Set instance name and host facts
      set_fact:
        instance_name={{ cluster }}-{{ seq }}
        play_host_vars={{ play_hosts | map('extract', hostvars) | list }}

    - name: Build addional facts from inventory
      set_fact: version={{ version | trim | default(12)  }}
        cluster_count={{ play_host_vars | json_query('[].cluster')  | unique | length  }}
        seq_list={{ play_host_vars | json_query('[].seq')  | list  }}
        cluster_size={{ play_host_vars | json_query('[].seq')  | unique | length }}
        seq_count={{ play_host_vars | json_query('length([].seq)') | int }}
        seq_min={{ play_host_vars | json_query('min([].seq)') | int }}
        seq_max={{ play_host_vars | json_query('max([].seq)') | int }}
        seq_next={{ play_host_vars | json_query('max([].seq)') | int + 1}}
        primary_count={{ play_host_vars | json_query("length([?role=='primary'].inventory_hostname)") | int }}
        replica_ips={{ play_host_vars | json_query("[?role!='primary'].inventory_hostname") }}
        primary_ip={{ play_host_vars | json_query("[?role=='primary'].inventory_hostname | [0]")}}
        play_host_vars=""

    - name: Check all hosts in same cluster
      assert:
        that: cluster_count|int == 1
        fail_msg: "init cluster only works on one and only one cluster"

    - name: Check cluster primary singleton
      assert:
        that: primary_count|int == 1
        fail_msg: "init cluster require one and only one primary in cluster"

    - name: Set replica replication source
      set_fact:
        replication_source={{ upstream_ip|default(primary_ip) }}

    - name: Build group based on role fact
      group_by:
        key: "{{ role }}"

...