---
#-----------------------------------------------------------------
# PROMETHEUS
#-----------------------------------------------------------------
prometheus_enabled: true        # setup prometheus on meta node?
prometheus_data_dir: /data/prometheus/data         # prometheus data dir
prometheus_options: '--storage.tsdb.retention=15d' # prometheus cli args
prometheus_reload: false        # reload prometheus instead of recreate it?
prometheus_sd_method: static    # service discovery method: static|consul
prometheus_sd_interval: 5s      # service discovery refresh interval
prometheus_scrape_interval: 10s # global scrape & evaluation interval
prometheus_scrape_timeout: 8s   # scrape timeout

#-----------------------------------------------------------------
# EXPORTER (Reference)
#-----------------------------------------------------------------
exporter_metrics_path: /metrics  # default metric path for pg related exporter
#-----------------------------------------------------------------
# DCS (Reference)
#-----------------------------------------------------------------
dcs_servers: {}                  # dcs server dict in name:ip format
etcd_enabled: true               # enable etcd server by default?
#-----------------------------------------------------------------
# NODE_EXPORTER (Reference)
#-----------------------------------------------------------------
node_exporter_port: 9100         # default port for node exporter
#-----------------------------------------------------------------
# PG_EXPORTER (Reference)
#-----------------------------------------------------------------
pg_exporter_port: 9630           # pg_exporter listen port
pgbouncer_exporter_port: 9631    # pgbouncer_exporter listen port
#-----------------------------------------------------------------
# PG_SERVICE (Reference)
#-----------------------------------------------------------------
haproxy_exporter_port: 9101      # default admin/exporter port
...