---
################################################################
# PHASE 1: [check] primary instance precondition
################################################################
- name: Check replica environment
  tags: [always, pg_replica_check]
  block:
    - name: Check replica pg version {{ version }}
      shell: "[[ $(/usr/pgsql/bin/pg_ctl --version) == 'pg_ctl (PostgreSQL) {{ version }}'* ]]"

    # if postgres exists, if will abort, unless specify force to skip this check
    - name: Check replica not running (set force=on to skip)
      when: not force
      shell: "ps aux | grep -v grep | grep -- '-D /pg/data' | grep pgsql || exit 0 && exit 1"

    - name: Set replica facts
      set_fact:
        default_pg_hba_conf: "pg_hba-replica.conf"
        replication_source: "{{ upstream_ip | default(primary_ip) }}"



################################################################
# PHASE 2: [clean] existing stuff
################################################################
# DANGEROUS! remove all postgres data of target machine
- name: Cleanup postgresql
  tags: pg_replica_clean
  block:
    - name: Stop running postgres replica
      ignore_errors: true
      systemd: name=postgres state=stopped enabled=no daemon_reload=yes

    # in case that postgres is start manually via pg_ctl
    - name: Stop running postgres replica manull
      become_user: postgres
      shell: |
        pg_exist=$(ps aux | grep -v grep | grep -- '-D /pg/data' | grep pgsql | wc -l)
        if (( $pg_exist==1 )); then
            /usr/pgsql/bin/pg_ctl -D /pg/data stop
        fi
        exit 0

    - name: Remove existing /pg/data directory
      file: path=/pg/data state=absent

    - name: Recreate /pg/data directory
      file: path=/pg/data state=directory owner=postgres group=postgres mode=0700



################################################################
# PHASE 3: [initdb] create database cluster
################################################################
- name: Init database replica from primary
  tags: pg_replica_init
  block:
    - name: Write pgpass according to default setting
      copy:
        content: |
          *:*:*:{{ replication_username }}:{{ replication_password }}
          *:*:*:{{ monitor_username }}:{{ monitor_password }}
        dest: /home/postgres/.pgpass
        owner: postgres
        group: postgres
        mode: 0600

    # add default user/pass to pgpass
    - name: Create pgpass contains replicator info
      when: default_creation is defined and default_creation|bool
      lineinfile:
        path: /home/postgres/.pgpass
        line: "*:*:*:{{ default_username }}:{{ default_password }}"
        create: yes

    # check primary is available
    - name: Check replica connectivity to upstream
      become_user: postgres
      command: psql -h {{ primary_ip }} -U {{ replication_username }} -d postgres -Atc 'SELECT 1;'

    # create basebackup from primary
    - name: Create basebackup from primary
      become_user: postgres
      command: /usr/pgsql/bin/pg_basebackup -h {{ primary_ip }} -U {{ replication_username }} -D /pg/data -Fp -Xs -Pv -R -c fast
      async: 0



################################################################
# PHASE 4: [config] postgres
################################################################
# use custome postgresql.conf via ( override with -e pgconf=/path/to/postgresql.conf )
- name: Config postgresql replica
  tags: pg_replica_config
  block:
    - name: Copy replica postgresql.conf of version {{ version }}
      when: postgresql_conf_path is defined
      template:
        src: "{{ postgresql_conf_path }}"
        dest: /pg/data/postgresql.conf
        owner: postgres
        group: postgres
        mode: 0600

    - name: Copy replica pg_hba.conf if provided
      template:
        src: "{{ replica_pg_hba_path | default(default_pg_hba_conf) }}"
        dest: /pg/data/pg_hba.conf
        owner: postgres
        group: postgres
        mode: 0600

    # cascade replication could be achieved here
    - name: Setup replica replication source
      tags: [config_replica]
      lineinfile:
        path: /pg/data/postgresql.auto.conf
        regexp: "^primary_conninfo"
        line: "primary_conninfo = 'host={{ replication_source }} port=5432  application_name=''{{ instance_name }}'' user=''{{ replication_username }}'' passfile=''/home/postgres/.pgpass'''"
        owner: postgres
        group: postgres
        mode: 0600




################################################################
# PHASE 5: [launch] postgresql service
################################################################
# launch postgres @ default 5432 port
- name: Launch PostgreSQL service
  tags: pg_primary_launch
  block:
    - name: Start postgres service
      systemd: name=postgres state=restarted enabled=yes daemon_reload=yes

    - name: Waits postgres listen on port
      wait_for: host=localhost port=5432 state=started timeout=10

    - name: Check postgres is ready
      become_user: postgres
      command: /usr/pgsql/bin/pg_isready
